--Questions:
--1. Best-Performing Product Categories
--Snapdeal wants to focus on product categories that consistently exceed their sales targets to 
--guide future marketing and inventory decisions. To analyse this, you will need to compare the total revenue 
--generated by each category to the target for that category in the month of April 2018.

-- Expected Output Columns:
-- Category: The name of the product category.
-- Total Sales: The total revenue generated by that category in April 2018.
-- Sales Target: The target revenue for that category in April 2018.

SELECT d.category, sum(d.amount * d.quantity) as Total_Sales , sum(t.target)  as Sales_Target
FROM order_details d
LEFT JOIN sales_target t
ON d.category = t.category
WHERE t.month_of_order = 'Apr-18'
GROUP BY d.category
ORDER BY Total_Sales DESC;




-- 2. Customer Purchase Behavior by Location
-- Snapdeal wants to understand how customer purchasing behavior varies by location, particularly which states contribute 
--the most orders. Write an SQL query to identify the top 3 states with the highest number of orders.

-- Expected Output Columns:
-- State: The state where the orders originated.
-- Total Orders: The total number of orders placed from that state.

SELECT state,count(order_id) AS Total_Orders FROM order_list
GROUP BY state
ORDER BY Total_Orders DESC
LIMIT 3;



-- 3. High Revenue, Low Profit Products
-- Snapdeal is interested in identifying products that generate significant revenue but contribute little to overall profit. 
-- These products might require pricing adjustments or cost reductions. To help with this, you will need to categorize 
-- products based on their profit margins and identify those with high revenue but low profitability. 
-- Write an SQL query to identify products that generate more than $10,000 in revenue but have a 
-- profit margin of less than 5% and classify products as having either a “Low Profit Margin” or a “High Profit Margin” 
-- based on their total revenue and total profit.

-- Expected Output Columns:
-- Category: The product category.
-- Sub-Category: The product sub-category.
-- Total Revenue: The total revenue generated by that product.
-- Total Profit: The total profit generated by that product.
-- Profit Margin Category: Categorizes products as "Low Profit Margin" or "High Profit Margin" based on the profit margin.

WITH product_summary AS (
    SELECT
        category,
        sub_category,
        sum(amount * quantity) AS total_revenue,
        SUM(profit) AS total_profit,
        CASE 
            WHEN SUM(amount) = 0 THEN 0
            ELSE SUM(profit) / SUM(amount)
        END AS profit_margin
    FROM order_details
    GROUP BY category, sub_category
)
SELECT
    category,
    sub_category,
    total_revenue,
    total_profit,
    ROUND(profit_margin * 100, 2) AS profit_margin_pct,
    CASE
        WHEN profit_margin < 0.05 THEN 'Low Profit Margin'
        ELSE 'High Profit Margin'
    END AS profit_margin_category
FROM product_summary
WHERE total_revenue > 10000
ORDER BY total_revenue DESC;




-- 4. Products with Highest Profit per Sale
-- Snapdeal is looking to identify the products with the highest profit per unit sold. This will help 
-- inform decisions about which products to promote or prioritize in inventory. Write an SQL query to 
-- calculate the profit per unit for each product.

-- Expected Output Columns:
-- Category: The product category.
-- Sub-Category: The product sub-category.
-- Total Profit: The total profit generated by that product.
-- Total Quantity: The total number of units sold.
-- Profit per Unit: The calculated profit per unit sold.

select category,sub_category, sum(profit) as total_profit,sum(quantity) as total_quantity , 
round(sum(profit) / sum(quantity) ,2) as profit_per_unit
FROM order_details
GROUP BY  category, sub_category
ORDER BY profit_per_unit DESC;






-- 5. Set Operations for Category Comparison
-- Snapdeal wants to explore cross-sell opportunities by identifying customers who have purchased 
-- from multiple product categories. This will help them understand which customers are more likely 
-- to buy products from different categories. Write an SQL query to identify customers who purchased from multiple categories.

-- Expected Output Columns:
-- CustomerName: The name of the customer.
-- Unique Categories: The number of different categories the customer has purchased from.

SELECT ol.customer_name,count(distinct od.category) AS unique_category
FROM order_list ol
JOIN order_details od
ON od.order_id = ol.order_id
GROUP BY ol.customer_name
ORDER BY unique_category DESC;




-- 6. Product Revenue Comparison
-- Snapdeal wants to identify products that consistently outperform other products in the same category 
-- in terms of revenue. This will help guide future acquisition and promotional strategies.
-- Write an SQL query to identify products whose total sales are higher than the average sales for other products in the same category.

-- Expected Output Columns:
-- Category: The product category.
-- Sub-Category: The product sub-category.
-- Total Revenue: The total revenue generated by that product.
-- Q6 Corrected: Products (sub-categories) with revenue > average revenue in same category

WITH category_totals AS (
    SELECT
        category,
        sub_category,
        SUM(amount * quantity) AS total_revenue
    FROM order_details
    GROUP BY category, sub_category
),
category_avg AS (
    SELECT
        category,
        AVG(total_revenue) AS avg_revenue_in_category
    FROM category_totals
    GROUP BY category
)
SELECT
    ct.category AS Category,
    ct.sub_category AS "Sub-Category",
    ct.total_revenue AS "Total Revenue"
FROM category_totals ct
JOIN category_avg ca
    ON ct.category = ca.category
WHERE ct.total_revenue > ca.avg_revenue_in_category
ORDER BY ct.category, ct.total_revenue DESC;
